// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import * as Igor from './igor';

export class Stub {
    static fromJson(json: Igor.Json.JsonValue): Stub {
        const obj = new Stub();
        return obj;
    }

    static toJson(value: Stub): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return Stub.toJson(this);
    }
}
